/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2023-03-31 09:47:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import ucl.ac.uk.model.Item;
import ucl.ac.uk.model.List;
import java.util.Objects;

public final class work5_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Objects");
    _jspx_imports_classes.add("ucl.ac.uk.model.Item");
    _jspx_imports_classes.add("ucl.ac.uk.model.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, Helvetica, sans-serif;\n");
      out.write("        }\n");
      out.write("        .column {\n");
      out.write("            float: left;\n");
      out.write("            width: 23.6%;\n");
      out.write("            padding: 0 10px;\n");
      out.write("        }\n");
      out.write("        .row {margin: 0 -5px;}\n");
      out.write("        .row:after {\n");
      out.write("            content: \"\";\n");
      out.write("            display: table;\n");
      out.write("            clear: both;\n");
      out.write("        }\n");
      out.write("        .card {\n");
      out.write("            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);\n");
      out.write("            padding: 5px;\n");
      out.write("            text-align: left;\n");
      out.write("            background-color: #f1f1f1;\n");
      out.write("            height: 220px;\n");
      out.write("        }\n");
      out.write("        @media screen and (max-width: 600px) {\n");
      out.write("            .column {\n");
      out.write("                width: 100%;\n");
      out.write("                display: block;\n");
      out.write("                margin-bottom: 20px;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("    <title>List example</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");

        ArrayList<ArrayList<Item>> allLists = (ArrayList<ArrayList<Item>>) application.getAttribute("allLists");
        if (allLists == null) {
            allLists = new ArrayList<>();
            application.setAttribute("allLists", allLists);
        }
    
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");

        int listIndex = -1;
        String selectedList = request.getParameter("selectedList");
        if (selectedList != null) {
            try {
                listIndex = Integer.parseInt(selectedList);
            } catch (NumberFormatException e) {
                // ignore, listIndex will remain -1
            }
        }
        ArrayList<Item> list = null;
        if (listIndex >= 0 && listIndex < allLists.size()) {
            list = allLists.get(listIndex);
        }
        if (list == null) {
            list = new ArrayList<>();
            allLists.add(list);
            listIndex = allLists.size() - 1;
        }

        String deleteList = request.getParameter("deleteList");
        if (deleteList != null) {
            String listIndexStr = request.getParameter("listIndex");
            if (listIndexStr != null) {
                try {
                    int index = Integer.parseInt(listIndexStr);
                    if (index >= 0 && index < allLists.size()) {
                        allLists.remove(index);
                        if (index == listIndex) {
                            listIndex = -1;
                            list = null;
                        } else if (index < listIndex) {
                            listIndex--;
                        }
                    }
                } catch (NumberFormatException e) {
                    // ignore
                }
            }
        }
    
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");

        String newList = request.getParameter("newList");
        if (newList != null && !newList.trim().isEmpty()) {
            list = new ArrayList<>();
            allLists.add(list);
            listIndex = allLists.size() - 1;
        }
    
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");

        String itemText = request.getParameter("itemText");
        String itemUrl = request.getParameter("itemUrl");
        String itemImage = request.getParameter("itemImage");


        if (itemText != null && !itemText.trim().isEmpty()) {
            Item item = new Item(itemText, "", "");
            assert list != null;
            list.add(item);
        } else if (itemUrl != null && !itemUrl.trim().isEmpty()) {
            Item item = new Item("", itemUrl, "");
            assert list != null;
            list.add(item);
        } else if (itemImage != null && !itemImage.trim().isEmpty()) {
            Item item = new Item("", "", itemImage);
            assert list != null;
            list.add(item);
        }

        String listName_a = null; //request.getParameter("listName_a");

        String newListName_a = request.getParameter("listName");
        if (newListName_a != null) {
            listName_a = newListName_a;
      }
    
      out.write("\n");
      out.write("\n");
      out.write("    ");

        String deleteElement = request.getParameter("deleteElement");
        if (deleteElement != null) {
            String elemIndexStr = request.getParameter("elemIndex");
            if (elemIndexStr != null) {
                try {
                    int index_x = Integer.parseInt(elemIndexStr);
                    assert list != null;
                    list.remove(index_x);
                    } catch (NumberFormatException e) {
                    // ignore
                }
            }
        }
    
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");

        // CHANGE TEXT
        String changeText = request.getParameter("change_itemText");
        String change_elemIndexStr = request.getParameter("edit_text_elem_index");
        try {
            if (changeText != null) {
                if (change_elemIndexStr != null) {
                    Item item = new Item(changeText, "", "");
                    assert list != null;
                    list.set(Integer.parseInt(change_elemIndexStr), item);
                }
            }
        } catch (NumberFormatException e) {
            // ignore
        }
//        if (changeText != null) {
//            String change_elemIndexStr = request.getParameter("edit_text_elem_index");
//            if (change_elemIndexStr != null) {
//                try {
//                    Item item = new Item(changeText, "", "");
//                    list.set(Integer.parseInt(change_elemIndexStr), item);
//                } catch (NumberFormatException e) {
//                    // ignore
//                }
//            }
//        }
//
        // CHANGE URL
        String changeURL = request.getParameter("change_itemUrl");
        if (changeURL != null) {
            String change_elemIndexStr_b = request.getParameter("edit_url_elem_index");
            if (change_elemIndexStr_b != null) {
                try {
                    Item item = new Item("", changeURL, "");
                    assert list != null;
                    list.set(Integer.parseInt(change_elemIndexStr_b), item);
                } catch (NumberFormatException e) {
                    // ignore
                }
            }
        }

        // CHANGE IMAGE
        String changeImage = request.getParameter("change_itemImage");
        if (changeImage != null) {
            String change_elemIndexStr_c = request.getParameter("edit_image_elem_index");
            if (change_elemIndexStr_c != null) {
                try {
                    Item item = new Item("", "", changeImage);
                    assert list != null;
                    list.set(Integer.parseInt(change_elemIndexStr_c), item);
                } catch (NumberFormatException e) {
                    // ignore
                }
            }
        }
    
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <form method=\"post\">\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("            <div class=\"column\">\n");
      out.write("                <div class=\"card\" >\n");
      out.write("\n");
      out.write("                    <h3>Search List: </h3>\n");
      out.write("                    <label>Select list:</label>\n");
      out.write("                    <label>\n");
      out.write("                        <select name=\"selectedList\">\n");
      out.write("                            ");
 for (int i = 0; i < allLists.size(); i++) { 
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( i );
      out.write('"');
      out.write(' ');
      out.print( i == listIndex ? "selected" : "" );
      out.write('>');
      out.print( "List " + (i+1));
      out.write("</option>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </label>\n");
      out.write("                    <input type=\"submit\" value=\"View List\">\n");
      out.write("\n");
      out.write("                    <h3>Delete Element: </h3>\n");
      out.write("                    <label>Select element index:</label>\n");
      out.write("                    <label>\n");
      out.write("                        <select name=\"elemIndex\">\n");
      out.write("                            ");
 for (int i = 0; i < Objects.requireNonNull(list).size(); i++) { 
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( i );
      out.write('"');
      out.write(' ');
      out.print( "Element selected: "  );
      out.write('>');
      out.print( "Element " + (i+1));
      out.write("</option>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </label>\n");
      out.write("                    <input type=\"submit\" name=\"deleteElement\" value=\"Delete element\">\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"column\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <h3>Add Elements To The List: </h3>\n");
      out.write("                    <label>\n");
      out.write("                        <input placeholder=\"Text\" type=\"text\" name=\"itemText\">\n");
      out.write("                    </label><input type=\"submit\" value=\"Add Text\"><br>\n");
      out.write("                    <br>\n");
      out.write("                    <label>\n");
      out.write("                        <input placeholder=\"URL\" type=\"text\" name=\"itemUrl\">\n");
      out.write("                    </label><input type=\"submit\" value=\"Add URL\"><br>\n");
      out.write("                    <br>\n");
      out.write("                    <label>\n");
      out.write("                        <input placeholder=\"Image URL\" type=\"text\" name=\"itemImage\">\n");
      out.write("                    </label><input type=\"submit\" value=\"Add Image\"><br>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"column\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <h3>Edit Elements In The List: </h3>\n");
      out.write("                    <label>\n");
      out.write("                        <select name=\"edit_text_elem_index\">\n");
      out.write("                            ");
 for (int i = 0; i < list.size(); i++) { 
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( "Element " + (i+1) );
      out.write("</option>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </label>\n");
      out.write("                    <label>\n");
      out.write("                        <input placeholder=\"Text\" type=\"text\" name=\"change_itemText\">\n");
      out.write("                    </label><input type=\"submit\" value=\"Change Text\"><br>\n");
      out.write("                    <br>\n");
      out.write("                    <label>\n");
      out.write("                        <select name=\"edit_url_elem_index\">\n");
      out.write("                            ");
 for (int i = 0; i < list.size(); i++) { 
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( "Element " + (i+1) );
      out.write("</option>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </label>\n");
      out.write("                    <label>\n");
      out.write("                        <input placeholder=\"URL\" type=\"text\" name=\"change_itemUrl\">\n");
      out.write("                    </label><input type=\"submit\" value=\"Change URL\"><br>\n");
      out.write("                    <br>\n");
      out.write("                    <label>\n");
      out.write("                        <select name=\"edit_image_elem_index\">\n");
      out.write("                            ");
 for (int i = 0; i < list.size(); i++) { 
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( "Element " + (i+1) );
      out.write("</option>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </label>\n");
      out.write("                    <label>\n");
      out.write("                        <input placeholder=\"Image URL\" type=\"text\" name=\"change_itemImage\">\n");
      out.write("                    </label><input type=\"submit\" value=\"Change Image\"><br>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"column\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <h3>List Options</h3>\n");
      out.write("\n");
      out.write("                        ");
      out.write("\n");
      out.write("                        <input name=\"newList\" type=\"submit\" value=\"Create New List\"><br><br>\n");
      out.write("\n");
      out.write("                        ");
      out.write("\n");
      out.write("                    <label>\n");
      out.write("                        <select name=\"listIndex\">\n");
      out.write("                            ");
 for (int i = 0; i < allLists.size(); i++) { 
      out.write("\n");
      out.write("                                <option value=\"");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( "List " + (i+1) );
      out.write("</option>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </label>\n");
      out.write("                    <input type=\"submit\" name=\"deleteList\" value=\"*Delete Selected List\"><br><br>\n");
      out.write("\n");
      out.write("                        ");
      out.write("\n");
      out.write("                    <label>\n");
      out.write("                        <input type=\"text\" name=\"listName\" placeholder=\"Enter new name...\">\n");
      out.write("                    </label>\n");
      out.write("                    <button type=\"submit\">**Rename</button>\n");
      out.write("                        <h6>*When deleting a list, the list on screen must not be the list you want to delete.\n");
      out.write("                            **Name of list is the first element of the list</h6>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <hr>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <h2>");
      out.print( "List " + (listIndex+1) + " - " + listName_a + ": ");
      out.write("</h2>\n");
      out.write("    <ul>\n");
      out.write("        ");
 for (Item item : list) { 
      out.write("\n");
      out.write("        <li>");
      out.print( item.toString() );
      out.write("</li>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </ul>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
